2021-03-12 07:18:32 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at gal.teis.conexion.ConexionSingleton.<init>(ConexionSingleton.java:88)
	at gal.teis.conexion.ConexionSingleton.getConnection(ConexionSingleton.java:64)
	at gal.teis.db.aplicacion.Principal.main(Principal.java:60)
Caused by: org.h2.jdbc.JdbcSQLException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 21 more
2021-03-12 07:19:29 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at gal.teis.conexion.ConexionSingleton.<init>(ConexionSingleton.java:88)
	at gal.teis.conexion.ConexionSingleton.getConnection(ConexionSingleton.java:64)
	at gal.teis.db.aplicacion.Principal.main(Principal.java:60)
Caused by: org.h2.jdbc.JdbcSQLException: Error General : "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]" [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:D:/IES/6_Teis/Proxectos-AD-PGR/AD-UD2-Conectores-JDBC-H2/data/biblioteca.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 21 more
2021-03-12 07:23:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:23:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:23:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:28:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:28:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:44:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:44:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:45:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:45:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:46:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:49:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:49:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:49:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:49:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:51:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:52:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:53:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:54:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:57:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 07:59:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 08:01:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
2021-03-12 08:22:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: El objeto ya está cerrado
The object is already closed [90007-196]
